import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css"
import Link from "next/link";
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  { name: 'Home', href: '/' },
  { name: 'About', href: '/about' },
  { name: 'Services', href: '/services' },
  { name: 'Contact', href: '/contact' },
  { name: 'User', href: '/user' },
  { name: 'Project', href: '/project' },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.gridLayout}>
          <header className={styles.header}>
            {
              navLinks.map((link) => {
                return (
                  <Link
                    key={link.href}
                    href={link.href}
                    className="text-blue-600 p-3 flex hover:underline"
                  >
                    {link.name}
                  </Link>
                )
              })
            }

          </header>



          <nav className={styles.sidebar}>Sidebar</nav>
          <main className={styles.main}>{children}</main>
          <footer className={styles.footer}>Footer</footer>
        </div>

      </body>
    </html>
  );
}
